// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice = EducationSlice | WorkSlice | HeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<PageDocumentData>,
  'page',
  Lang
>;

export type AllDocumentTypes = PageDocument;

/**
 * Item in *Education → Default → Primary → Education Item*
 */
export interface EducationSliceDefaultPrimaryEducationItemItem {
  /**
   * Education Title field in *Education → Default → Primary → Education Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: education.default.primary.education_item[].education_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  education_title: prismic.KeyTextField;

  /**
   * Education Description field in *Education → Default → Primary → Education Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: education.default.primary.education_item[].education_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  education_description: prismic.KeyTextField;

  /**
   * Education Dates field in *Education → Default → Primary → Education Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: education.default.primary.education_item[].education_dates
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  education_dates: prismic.KeyTextField;

  /**
   * Education URL field in *Education → Default → Primary → Education Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: education.default.primary.education_item[].education_url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  education_url: prismic.KeyTextField;

  /**
   * Education Icon field in *Education → Default → Primary → Education Item*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: education.default.primary.education_item[].education_icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  education_icon: prismic.ImageField<never>;

  /**
   * Education Icon Color field in *Education → Default → Primary → Education Item*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: education.default.primary.education_item[].education_icon_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  education_icon_color: prismic.ColorField;
}

/**
 * Primary content in *Education → Default → Primary*
 */
export interface EducationSliceDefaultPrimary {
  /**
   * Education Heading field in *Education → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: education.default.primary.education_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  education_heading: prismic.KeyTextField;

  /**
   * Education Item field in *Education → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: education.default.primary.education_item[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  education_item: prismic.GroupField<Simplify<EducationSliceDefaultPrimaryEducationItemItem>>;
}

/**
 * Default variation for Education Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EducationSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<EducationSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Education*
 */
type EducationSliceVariation = EducationSliceDefault;

/**
 * Education Shared Slice
 *
 * - **API ID**: `education`
 * - **Description**: Education
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EducationSlice = prismic.SharedSlice<'education', EducationSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Hello World field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hello_world
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hello_world: prismic.KeyTextField;

  /**
   * Profile Picture field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.profile_picture
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  profile_picture: prismic.ImageField<never>;

  /**
   * First Name field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.first_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  first_name: prismic.KeyTextField;

  /**
   * Last Name field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.last_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  last_name: prismic.KeyTextField;

  /**
   * Tag Line field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.tag_line
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tag_line: prismic.KeyTextField;

  /**
   * About Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.about_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  about_heading: prismic.KeyTextField;

  /**
   * About Line field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.about_line
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  about_line: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<'default', Simplify<HeroSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<'hero', HeroSliceVariation>;

/**
 * Item in *Work → Default → Primary → Work Item*
 */
export interface WorkSliceDefaultPrimaryWorkItemItem {
  /**
   * Work Title field in *Work → Default → Primary → Work Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work.default.primary.work_item[].work_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  work_title: prismic.KeyTextField;

  /**
   * Work Description field in *Work → Default → Primary → Work Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work.default.primary.work_item[].work_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  work_description: prismic.KeyTextField;

  /**
   * Work Dates field in *Work → Default → Primary → Work Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work.default.primary.work_item[].work_dates
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  work_dates: prismic.KeyTextField;

  /**
   * Work URL field in *Work → Default → Primary → Work Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work.default.primary.work_item[].work_url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  work_url: prismic.KeyTextField;

  /**
   * Work Icon field in *Work → Default → Primary → Work Item*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: work.default.primary.work_item[].work_icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  work_icon: prismic.ImageField<never>;

  /**
   * Work Icon Color field in *Work → Default → Primary → Work Item*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: work.default.primary.work_item[].work_icon_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  work_icon_color: prismic.ColorField;
}

/**
 * Primary content in *Work → Default → Primary*
 */
export interface WorkSliceDefaultPrimary {
  /**
   * Work Heading field in *Work → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work.default.primary.work_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  work_heading: prismic.KeyTextField;

  /**
   * Work Item field in *Work → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: work.default.primary.work_item[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  work_item: prismic.GroupField<Simplify<WorkSliceDefaultPrimaryWorkItemItem>>;
}

/**
 * Default variation for Work Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkSliceDefault = prismic.SharedSliceVariation<'default', Simplify<WorkSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Work*
 */
type WorkSliceVariation = WorkSliceDefault;

/**
 * Work Shared Slice
 *
 * - **API ID**: `work`
 * - **Description**: Work
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkSlice = prismic.SharedSlice<'work', WorkSliceVariation>;

declare module '@prismicio/client' {
  interface CreateClient {
    (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (repositoryNameOrEndpoint: string, options: prismic.WriteClientConfig): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      EducationSlice,
      EducationSliceDefaultPrimaryEducationItemItem,
      EducationSliceDefaultPrimary,
      EducationSliceVariation,
      EducationSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      WorkSlice,
      WorkSliceDefaultPrimaryWorkItemItem,
      WorkSliceDefaultPrimary,
      WorkSliceVariation,
      WorkSliceDefault
    };
  }
}
